// Path -> destination map for legacy albatros.uz URLs discovered via the
// Wayback Machine CDX crawl (scripts/wayback-sitemap.mjs, see
// scripts/wayback-sitemap-albatros_uz-combined.txt). The old site slugified
// product names with underscores and appended a random 5-6 char id
// (e.g. "/product/maglumi_x3-OZsvB"); none of that survives on the new site,
// so old visitors and indexed search results 404 without this table.
//
// Where the old product still exists under the new catalog it redirects
// straight to /product/<new-slug>; where it was discontinued or merged, it
// falls back to the closest still-live page (a brand's /partners/<id> page,
// or /catalog as a last resort) so link equity and visitors land somewhere
// useful instead of a dead end.
export const legacyProductRedirects: Record<string, string> = {
  "/product/acl_top_350_cts-lgqqk": "/product/acl-top-350-cts",
  "/product/acl_top_350_cts-pxXaS": "/product/acl-top-350-cts",
  "/product/acl_top_550_cts-E7B8Q": "/partners/werfen",
  "/product/acusera-rdLsL": "/product/acusera",
  "/product/bd_bactec_fx_40-09f6m": "/product/bd-bactec-fx40",
  "/product/bd_bactec_fx_40-AooXY": "/product/bd-bactec-fx40",
  "/product/bd_phoenix_m50-fBYYg": "/product/bd-phoenix-m50",
  "/product/bd_phoenix_m50-k9HFe": "/product/bd-phoenix-m50",
  "/product/biolumi_cx8-1ZGMK": "/partners/snibe",
  "/product/biolumi_cx8-qS6Ci": "/partners/snibe",
  "/product/biolumi_cx8-rt2j2": "/partners/snibe",
  "/product/biolumi_cx_solution-wvwgO": "/product/biolumi-cx-solution",
  "/product/biossays_240_plus-Df9U0": "/product/biossays-240-plus",
  "/product/biossays_240_plus-T9CL6": "/product/biossays-240-plus",
  "/product/biossays_240_plus-yGd6u": "/product/biossays-240-plus",
  "/product/biossays_c10-fcPgz": "/product/biossays-c10",
  "/product/biossays_c8-42yjN": "/product/biossays-c8",
  "/product/biossays_c8-PROLr": "/product/biossays-c8",
  "/product/biossays_e6-1Cra4": "/partners/snibe",
  "/product/biossays_e6-DJrot": "/partners/snibe",
  "/product/biossays_e6-zvmOd": "/partners/snibe",
  "/product/blozer_200-GXlPu": "/product/blozer-200",
  "/product/blozer_72-DejnD": "/product/blozer-72",
  "/product/bq-50-nko2D": "/catalog",
  "/product/clarius_hd3-dOCTR": "/partners/clarius",
  "/product/cube_30_touch-kEHXE": "/product/cube-30-touch",
  "/product/dymind_df50_crp-9V17u": "/product/df50-crp",
  "/product/dymind_df50_crp-aGbKU": "/product/df50-crp",
  "/product/dymind_df56_vet-wXcfG": "/product/df56-vet",
  "/product/dymind_dh-615-wNPMA": "/product/dh-615",
  "/product/dymind_dh-800-lndFk": "/product/dh-800",
  "/product/dymind_dh-88-1GiFp": "/product/dh-88",
  "/product/dymind_dh26-b6GEv": "/product/dh-26",
  "/product/dymind_dh26-lT2kr": "/product/dh-26",
  "/product/dymind_dh615-RdB63": "/product/dh-615",
  "/product/evidence_multistat-hbpaw": "/product/evidence-multistat",
  "/product/gem_premier_3500-gjDXs": "/product/gem-premier-3500",
  "/product/gem_premier_5000-Lnjg1": "/product/gem-premier-5000",
  "/product/h100_plus-mQZNG": "/product/h100-plus",
  "/product/improswab-uPVbD": "/catalog",
  "/product/improvacuter-cSoaE": "/catalog",
  "/product/iscan-n1aZ9": "/partners/illumina",
  "/product/iseq_100-FQMjV": "/partners/illumina",
  "/product/keyu_ku-f20-eK8mX": "/product/keyu-ku-f20",
  "/product/keyu_ku-f40-1U82Y": "/product/keyu-ku-f40",
  "/product/lifotronic_gh-900_plus-HaBuj": "/product/gh-900-plus",
  "/product/lifotronic_gh-900_plus-ZY0qE": "/product/gh-900-plus",
  "/product/lifotronic_h8-VkEMb": "/product/h8",
  "/product/lifotronic_h8-qUPa5": "/product/h8",
  "/product/lifotronic_h9-KNt9B": "/product/h9",
  "/product/lifotronic_h9-VPdKx": "/product/h9",
  "/product/maglumi_2000+-4eKwm": "/partners/snibe",
  "/product/maglumi_2000-ahLZa": "/partners/snibe",
  "/product/maglumi_4000+-co9Eg": "/partners/snibe",
  "/product/maglumi_600-0i5W7": "/product/maglumi-600",
  "/product/maglumi_600-dWkUd": "/product/maglumi-600",
  "/product/maglumi_800-SJhaW": "/product/maglumi-800",
  "/product/maglumi_800-WencH": "/product/maglumi-800",
  "/product/maglumi_800-ije7V": "/product/maglumi-800",
  "/product/maglumi_x10-fNN0l": "/product/maglumi-x10",
  "/product/maglumi_x3-OZsvB": "/product/maglumi-x3",
  "/product/maglumi_x3-QJDZv": "/product/maglumi-x3",
  "/product/maglumi_x6-2320n": "/product/maglumi-x6",
  "/product/maglumi_x8-0wXWz": "/product/maglumi-x8",
  "/product/miniseq-KalNU": "/partners/illumina",
  "/product/miseq_i100_series_sequencing_systems-yeK8u": "/product/miseq-i100",
  "/product/molecision_mp-32-wLCDv": "/product/molecision-mp-32",
  "/product/molecision_mp-96-X4W5u": "/product/molecision-mp-96",
  "/product/molecision_r8-3aepM": "/product/molecision-r8",
  "/product/molecision_s6-B7XJs": "/product/molecision-s6",
  "/product/molecision_s6-x4uxK": "/product/molecision-s6",
  "/product/molecision™_mp-96_32-jhoqI": "/product/molecision-mp-96",
  "/product/nextseq_550-BUEIc": "/product/nextseq-550",
  "/product/nextseq™_1000_&_nextseq_2000_sequencing_systems-PCBMO": "/product/nextseq-1000-2000",
  "/product/novaseq_6000-ugA9G": "/product/novaseq-6000",
  "/product/novaseq_x__and_novaseq_x_plus_sequencing_system-Pmn59": "/product/novaseq-x",
  "/product/phadia_200-iseRz": "/product/phadia-200",
  "/product/phadia_200-p85O2": "/product/phadia-200",
  "/product/phadia_200-z57eA": "/product/phadia-200",
  "/product/qcmd-laTYf": "/product/qcmd",
  "/product/qnostics-xqeaw": "/product/qnostics",
  "/product/riqas-gwoFJ": "/product/riqas",
  "/product/satlars_-_t8-5YnNQ": "/product/satlars-t8",
  "/product/sqa-io_+_sqa-vu-kG6fs": "/product/sqa-io-vu",
  "/product/urit_bf-730-Sk4KH": "/product/urit-bf-730",
  "/product/urit_bs_-_8000_series-w9djF": "/product/urit-bs-8000",
  "/product/urit_us-1000-7bxHm": "/product/urit-us-1000",
  "/product/urit_us-1680-4AKrc": "/product/urit-us-1680",
  "/product/urit_us-2000c-FZym6": "/product/urit-us-2000c",
  "/product/urit_us-2000c-rsFe3": "/product/urit-us-2000c",
  "/product/Биола_Алат-2-cYR7W": "/catalog",
  "/product/Наборы_для_ПЦР.-WM6IC": "/catalog",
  "/product/Реагенты_ИХЛА-IpnsE": "/product/reagenty-maglumi-ihla",
  "/product/Реагенты_ИХЛА-bOYCT": "/product/reagenty-maglumi-ihla",
  "/product/Реагенты_и_расходные_материалы-5Netz": "/catalog",
  "/product/Реагенты_и_расходные_материалы._Гемостаз.-yKgQU": "/product/reagenty-werfen-gemostaz",
  "/product/Реагенты_и_расходные_материалы._ИХЛА.-8Zjnx": "/product/reagenty-maglumi-ihla",
  "/product/Стол_для_maglumi_x3,_600_и_800-x0XUq": "/product/rashodniki-maglumi-x",
  "/product/Тромбоэластометр_rotem®_delta-EnMtV": "/partners/werfen",
  "/product/Тромбоэластометр_rotem®_delta-f0mwz": "/partners/werfen",
  "/products/1": "/catalog",
  "/products/10": "/catalog",
  "/products/13": "/catalog",
  "/products/14": "/catalog",
  "/products/15": "/catalog",
  "/products/17": "/catalog",
  "/products/18": "/catalog",
  "/products/19": "/catalog",
  "/products/2": "/catalog",
  "/products/20": "/catalog",
  "/products/21": "/catalog",
  "/products/22": "/catalog",
  "/products/23": "/catalog",
  "/products/24": "/catalog",
  "/products/26": "/catalog",
  "/products/28": "/catalog",
  "/products/29": "/catalog",
  "/products/4": "/catalog",
  "/products/7": "/catalog",
  "/products/8": "/catalog",
  "/products/9": "/catalog",
};
